<a href="https://colab.research.google.com/github/va4756/big_RaeJung/blob/main/MachineLearning_%EC%9D%B4%EC%83%81%EC%B2%A0_ML01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.Python 기초 및 데이터 처리

## 1.Pytnon 기초

### 1.1 변수선언

In [ ]:
tot = 5
name = '홍길동'

In [ ]:
print(tot)
print(name)

5
홍길동


In [ ]:
# 리스트
num1 = [1,2,3,4]
num1

[1, 2, 3, 4]

In [ ]:
# 튜플
num2 = (1,2,3,4)
num2

(1, 2, 3, 4)

In [ ]:
# 집합
num3 = {1,2,3,4}
num3

{1, 2, 3, 4}

In [ ]:
num1[1:3]

[2, 3]

## 2.Numpy

In [ ]:
num2 = [5,6,7,8]

In [ ]:
num = [num1, num2]
num

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
num1 + num2

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
import numpy as np

num1 = np.array(num1)
num1

array([1, 2, 3, 4])

In [ ]:
num2 = np.array(num2)
num2

array([5, 6, 7, 8])

In [ ]:
num1 + num2

array([ 6,  8, 10, 12])

In [ ]:
num = np.array([num1, num2])
num

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
num.shape

(2, 4)

In [ ]:
num[1, 3]

8

In [ ]:
num3 = num[:2, :2]
num3

array([[1, 2],
       [5, 6]])

In [ ]:
num3 = num[0:, 1:]
num3

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
# 열합계
num.sum(axis=0)

array([ 6,  8, 10, 12])

In [ ]:
# 행합계
num.sum(axis=1)

array([10, 26])

In [ ]:
#덧셈
np.add(num1, num2)

array([ 6,  8, 10, 12])

In [ ]:
np.dot(num1, num2)

70

## 3.Pandas